backend:
  name: github
  repo: beginner9111/hugo-PaperMod
  branch: master
  base_url: https://api.sveltia.org
  auth_endpoint: /auth

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "我的博文"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "正文内容", name: "body", widget: "markdown"}
